### ISSUE TITLE
Dockerized?

### ISSUE THREAD

**Issue by defconxt** [penxio/penx#17]
Any chance you'd build a docker container for this? I'd love to deploy this and use it to replace obsidian potentially. I just need a simple note taking app and this looks to be it.

If not I may take a shot at it, but unsure as I've never done it before. Cheers

**Comment by 0x-leen** [comment]
I'll do it later(docker container) after the core feature is stable.

**Comment by 0xzion** [comment]
I'll do it later(docker container) after the core feature is stable, Maybe in a few weeks.

**Comment by rosnovsky** [comment]
@0xzion If it's ok with you, I'd take a stab at this over the holidays.

**Comment by boka18** [comment]
Here is PR for that:
https://github.com/penxio/penx/pull/27

**Comment by 0xzion** [comment]
@defconxt @rosnovsky @boka18  Self-hosted deployment is now supported, I have written documentation for it, you guys can test it

**Comment by winamp8** [comment]
期待可以docker部署
