### ISSUE TITLE
装不了，是我网络问题么

### ISSUE THREAD

**Issue by wangyue168git** [penxio/penx#39]
<img width="877" alt="image" src="https://github.com/penxio/penx/assets/26454435/3b35fc99-a13c-451b-91aa-aca5977b69aa">

**Comment by wangyue168git** [comment]
<img width="474" alt="image" src="https://github.com/penxio/penx/assets/26454435/03f6bd82-8396-4e3a-9ee3-7066f7fec273">
删除节点后重进不了

**Comment by 0x-leen** [comment]
fixed

**Comment by 0xzion** [comment]
fixed
