### ISSUE TITLE
Error "input valid token " While Using Token generated in account setting 

### ISSUE THREAD

**Issue by zhangpengbo** [penxio/penx#51]
Experience Env: windows 10 Pro;

step1: get the token
login https://app.penx.io/, switch to account setting--> personal token,  Copy token after **Add** .

step 2:  open Penx and try to login
paste the token copy before,  Erroe occur _"Please input a valid token"_

**Comment by zhangpengbo** [comment]
be sure of that the token  inputed is same as the initial token.

**Comment by 0xzion** [comment]
Editor app domain is switched from https://penx.io to https://app.penx.io,  I will release a version desktop app with domain app.penx.io to fix this.

**Comment by zhangpengbo** [comment]
it works now . I can login the desktop version now . 
It seems this software is still in it's early stages?

**Comment by 0xzion** [comment]
Yes in early stage, check here for roadmap: https://www.penx.io/roadmap
