### ISSUE TITLE
login https://app.penx.io/ failed 

### ISSUE THREAD

**Issue by zhangpengbo** [penxio/penx#55]
seems sse  backend not works.

Request URL:
https://github.com/LatentArchitect/Notebook/sse
Request Method:
OPTIONS
Status Code:
404 Not Found
Remote Address:
198.18.0.44:443
Referrer Policy:
strict-origin-when-cross-origin

**Comment by zhangpengbo** [comment]
> where login failed? web or desktop? and what is https://github.com/LatentArchitect/Notebook/sse?
1. Try to log in my account on website from china mainland.
2. Catch the error above with Chrome Inspect tools. Don't know what is https://github.com/LatentArchitect/Notebook/sse, 
It seems that app.penx.io dependent on   https://github.com/LatentArchitect/Notebook/sse ?

3. Did not works on incognito mode  with Chrome both  on windows and mac ;

4. access from china mainland.
![Screenshot 2024-03-08 at 21 34 19](https://github.com/penxio/penx/assets/9437145/bd0326fb-a57d-4782-a583-3fdf03f22e25)

**Comment by zhangpengbo** [comment]
Update, It works on incognito mode. 
But it loads really slowly.

**Comment by zhangpengbo** [comment]
Update ,login with google account/github

**Comment by 0xzion** [comment]
I have found this bug. PenX's sync server is designed to be decentralized. so every body can register a sync server.
![image](https://github.com/penxio/penx/assets/145775220/70937e2c-864c-454b-98d7-91d41ede5c96)

**Comment by 0xzion** [comment]
I will do some limit for these dead syncs server.

**Comment by 0xzion** [comment]
@zhangpengbo Try to login again now, it should be ok now

**Comment by zhangpengbo** [comment]
It works now .
