### ISSUE TITLE
AppImage?

### ISSUE THREAD

**Issue by everythingability** [penxio/penx#64]
Hi,

I'm on Sonoma 14.5 (23F79) and when I download the app  I get an .AppImage file.

pen-x_0.3.28_amd64.AppImage 

...what do I do with that? 

Thanks

Tom

**Comment by 0xzion** [comment]
@everythingability Try to download the `.dmg` file:
![image](https://github.com/penxio/penx/assets/145775220/9af66c6d-c5dc-41e9-b370-b572e42a245f)
